spec-version:        0.36.0
name:                gtk-print
version:             0.1.1.0
github:              "mpilgrem/gtk-print"
license:             BSD-3-Clause
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "2025 Mike Pilgrem"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/mpilgrem/gtk-print#readme>

dependencies:
- base >= 4.7 && < 5
- gi-cairo
- gi-cairo-connector
- gi-cairo-render
- gi-gtk >= 4.0
- gi-pango
- gi-pangocairo
- haskell-gi-base
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  gtk-print:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
